import{spawn}from"node:child_process";
import{mkdtemp,rm,writeFile}from"node:fs/promises";
import{tmpdir}from"node:os";
import path from"node:path";

const edge="C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",port=9333,profile=await mkdtemp(path.join(tmpdir(),"monster-v4-qa-")),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const capture=process.argv.includes("--capture"),roundArg=process.argv.find(x=>x.startsWith("--rounds=")),rounds=roundArg?Math.max(1,Number(roundArg.split("=")[1])||1):20;
const browser=spawn(edge,["--headless=new","--disable-gpu","--no-first-run",`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,"about:blank"],{stdio:"ignore",windowsHide:true});
let ws,seq=0;const pending=new Map(),errors=[];
async function json(pathname){for(let i=0;i<60;i++){try{const r=await fetch(`http://127.0.0.1:${port}${pathname}`);if(r.ok)return r.json()}catch{}await sleep(100)}throw Error("Edge DevTools endpoint unavailable")}
function command(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))})}
function evaluate(expression){return command("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true}).then(r=>{if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result?.result?.value})}
async function waitFor(expression,timeout=6000){const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(expression))return true;await sleep(80)}throw Error(`Timed out: ${expression}${errors.length?` | ${errors.join(" | ")}`:""}`)}
async function rect(){return evaluate(`(()=>{const r=document.querySelector('.monster-wrap.target')?.getBoundingClientRect();return r&&({x:r.x+r.width/2,y:r.y+r.height/2})})()`)}
async function gesture(dx=0,dy=0,hold=20){const p=await rect();if(!p)throw Error("Monster target missing");await command("Input.dispatchMouseEvent",{type:"mousePressed",x:p.x,y:p.y,button:"left",buttons:1,clickCount:1});await sleep(hold);if(dx||dy)await command("Input.dispatchMouseEvent",{type:"mouseMoved",x:p.x+dx,y:p.y+dy,button:"left",buttons:1});await command("Input.dispatchMouseEvent",{type:"mouseReleased",x:p.x+dx,y:p.y+dy,button:"left",buttons:0,clickCount:1});await sleep(45)}
async function snapshot(){return evaluate(`({view:document.body.dataset.view,width:innerWidth,height:innerHeight,overflow:document.documentElement.scrollWidth-innerWidth,canvas:document.querySelectorAll('canvas').length,diag:window.__monsterGameDiagnostics||null,result:document.querySelector('#battleEnd')?.classList.contains('show')})`)}
async function screenshot(name){if(!capture)return;const r=await command("Page.captureScreenshot",{format:"png",fromSurface:true});await writeFile(path.resolve(`${name}.png`),Buffer.from(r.result.data,"base64"))}
async function round(index){await evaluate(`document.querySelector('[data-mode="${index%2?"emotion":"person"}"]').click()`);await evaluate(`(()=>{const e=document.querySelector('#ventInput');e.value=${JSON.stringify(index%2?"我特别怕别人超过我，越想越停不下来":"有个同事很能装，领导一来就抢功")};e.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#releaseBtn').click()})()`);await waitFor(`document.body.dataset.view==='battleView'&&window.__monsterGameDiagnostics?.combat`,8000);if(index===0){await sleep(450);await screenshot("qa-v4-battle")}for(let i=0;i<14;i++){const mode=await evaluate(`window.__monsterGameDiagnostics?.combat?.mode`);if(mode==="release")break;await gesture(0,0,520)}await waitFor(`window.__monsterGameDiagnostics?.combat?.mode==='release'`,4000);const moves=[[105,0,20],[-105,0,20],[0,-110,20],[0,110,20],[85,85,20],[0,0,540]];for(const move of moves)await gesture(...move);for(let i=0;i<8&&!await evaluate(`window.__monsterGameDiagnostics?.combat?.canFinish`);i++)await gesture(i%2?105:-105,0,20);await waitFor(`window.__monsterGameDiagnostics?.combat?.canFinish`,4000);await evaluate(`document.querySelector('#finishNowBtn').click()`);await waitFor(`document.querySelector('#finisherPanel').classList.contains('show')`);await evaluate(`document.querySelector('[data-finish]').click()`);await waitFor(`document.querySelector('#battleEnd').classList.contains('show')`,6500);if(index===0){await sleep(450);await screenshot("qa-v4-result")}if(index<rounds-1)await evaluate(`document.querySelector('#againBtn').click()`);else await evaluate(`document.querySelector('#endHomeBtn').click()`)}
const aiPayload={semanticCore:["抢功","表演"],semanticAliases:["邀功"],triggerConcepts:["credit","performative"],monsterName:"聚光奖牌盗兽",monsterConcept:"抢走成果并站到灯下",personality:"夸张自得",visualMetaphor:"会吸附奖牌的聚光台",visualTraits:["spotlight","medals","screen"],symbolicArmor:["领导的注视","冒领的奖牌"],arenaConcept:"stage",combatPersonality:["绕场炫耀","护住奖牌"],storyBeats:["奖牌碎裂"],introLines:["灯光归我。"],defiantLines:["功劳本来就该发光。"],crackedLines:["这只是舞台事故。"],breakdownLines:["别拿走灯。"],koLines:["……安静了。"],finisherFlavor:"熄灯",reusableElements:["奖牌","聚光灯"]};
async function aiBridgeCheck(){const text="同事爱抢功还很会装";await evaluate(`document.querySelector('[data-director="ai"]').click();document.querySelector('[data-mode="person"]').click()`);await evaluate(`(()=>{const e=document.querySelector('#ventInput');e.value=${JSON.stringify(text)};e.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#releaseBtn').click()})()`);await waitFor(`document.querySelector('#aiBridgeDialog').open`,6000);await evaluate(`document.querySelector('#aiJson').value='{}';document.querySelector('#aiImportBtn').click()`);await waitFor(`document.querySelector('#aiError').textContent.length>0`);await evaluate(`document.querySelector('#aiJson').value=${JSON.stringify(JSON.stringify(aiPayload))};document.querySelector('#aiImportBtn').click()`);await waitFor(`document.body.dataset.view==='battleView'&&window.__monsterGameDiagnostics?.combat`,6000);await evaluate(`document.querySelector('#battleView [data-back="home"]').click()`);await waitFor(`document.body.dataset.view==='homeView'`);await evaluate(`document.querySelector('[data-mode="person"]').click()`);await evaluate(`(()=>{const e=document.querySelector('#ventInput');e.value=${JSON.stringify(text)};e.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#releaseBtn').click()})()`);await waitFor(`document.body.dataset.view==='battleView'&&!document.querySelector('#aiBridgeDialog').open`,6000);await evaluate(`document.querySelector('#battleView [data-back="home"]').click()`);await waitFor(`document.body.dataset.view==='homeView'`)}

try{
  const pages=await json("/json/list"),page=pages.find(x=>x.type==="page");if(!page)throw Error("No Edge page target");ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject});ws.onmessage=event=>{const msg=JSON.parse(event.data);if(msg.id&&pending.has(msg.id)){const p=pending.get(msg.id);pending.delete(msg.id);msg.error?p.reject(Error(msg.error.message)):p.resolve(msg)}else if(msg.method==="Runtime.exceptionThrown"){const d=msg.params.exceptionDetails;errors.push(`${d?.exception?.description||d?.text} @ ${d?.url||"unknown"}:${(d?.lineNumber??-1)+1}:${(d?.columnNumber??-1)+1}`)}};
  await command("Runtime.enable");await command("Page.enable");await command("Network.enable");await command("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:1,mobile:true});await command("Page.navigate",{url:"http://127.0.0.1:4173"});await waitFor(`document.readyState==='complete'&&window.__monsterGameDiagnostics`,10000);await sleep(500);await evaluate(`(()=>{const t=document.querySelector('#menuSoundToggle');t.checked=false;t.dispatchEvent(new Event('change',{bubbles:true}))})()`);const home=await snapshot();if(home.width!==390||home.overflow>1||home.view!=="homeView")throw Error(`Home layout failed: ${JSON.stringify(home)}`);await screenshot("qa-v4-home");
  for(let i=0;i<rounds;i++)await round(i);await waitFor(`document.body.dataset.view==='homeView'`);await aiBridgeCheck();await sleep(300);const cleaned=await snapshot();if(cleaned.canvas!==0||cleaned.diag?.encounter)throw Error(`Battle cleanup failed: ${JSON.stringify(cleaned)}`);
  await evaluate(`navigator.serviceWorker.ready.then(()=>true)`);await sleep(1000);await command("Network.emulateNetworkConditions",{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await command("Page.reload",{ignoreCache:false});await waitFor(`document.readyState==='complete'&&window.__monsterGameDiagnostics`,10000);await sleep(500);await evaluate(`(()=>{document.querySelector('[data-director="offline"]').click();const t=document.querySelector('#menuSoundToggle');t.checked=false;t.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('[data-mode="emotion"]').click();const e=document.querySelector('#ventInput');e.value='离线时我还是很烦';e.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#releaseBtn').click()})()`);await waitFor(`document.body.dataset.view==='battleView'&&window.__monsterGameDiagnostics?.combat`,8000);await evaluate(`document.querySelector('#battleView [data-back="home"]').click()`);await waitFor(`document.body.dataset.view==='homeView'`);const offline=await snapshot();if(offline.view!=="homeView"||offline.overflow>1||offline.canvas!==0)throw Error(`Offline reload failed: ${JSON.stringify(offline)}`);if(errors.length)throw Error(`Browser exceptions: ${errors.join(" | ")}`);
  console.log(JSON.stringify({ok:true,rounds,home,cleaned,offline},null,2));
}finally{try{ws?.close()}catch{}browser.kill();await sleep(150);await rm(profile,{recursive:true,force:true})}
