import { spawn } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

const edge="C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",port=9334,sleep=ms=>new Promise(r=>setTimeout(r,ms));
const profile=await mkdtemp(path.join(tmpdir(),"monster-v41-qa-"));
const browser=spawn(edge,["--headless=new","--disable-gpu","--no-first-run",`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,"about:blank"],{stdio:"ignore",windowsHide:true});
let ws,seq=0;const pending=new Map(),errors=[];
async function endpoint(){for(let i=0;i<80;i++){try{const r=await fetch(`http://127.0.0.1:${port}/json/list`);if(r.ok)return r.json()}catch{}await sleep(100)}throw Error("Edge endpoint unavailable")}
function command(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))})}
async function evaluate(expression){const r=await command("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true});if(r.result?.exceptionDetails)throw Error(r.result.exceptionDetails.text);return r.result?.result?.value}
async function waitFor(expression,timeout=9000){const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(expression))return;await sleep(90)}throw Error(`Timeout: ${expression}`)}
async function center(selector){return evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)})?.getBoundingClientRect();return r&&{x:r.x+r.width/2,y:r.y+r.height/2}})()`)}
async function press(selector,hold=180,dx=0,dy=0){const p=await center(selector);if(!p)throw Error(`Missing ${selector}`);await command("Input.dispatchMouseEvent",{type:"mousePressed",x:p.x,y:p.y,button:"left",buttons:1});await sleep(hold);if(dx||dy)await command("Input.dispatchMouseEvent",{type:"mouseMoved",x:p.x+dx,y:p.y+dy,button:"left",buttons:1});await command("Input.dispatchMouseEvent",{type:"mouseReleased",x:p.x+dx,y:p.y+dy,button:"left",buttons:0});await sleep(80)}
async function shot(name){const r=await command("Page.captureScreenshot",{format:"png",fromSurface:true});await writeFile(path.resolve(name),Buffer.from(r.result.data,"base64"))}

try{
  const pages=await endpoint(),page=pages.find(x=>x.type==="page");ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject});
  ws.onmessage=event=>{const msg=JSON.parse(event.data);if(msg.id&&pending.has(msg.id)){const p=pending.get(msg.id);pending.delete(msg.id);msg.error?p.reject(Error(msg.error.message)):p.resolve(msg)}else if(msg.method==="Runtime.exceptionThrown")errors.push(msg.params.exceptionDetails?.exception?.description||msg.params.exceptionDetails?.text)};
  await command("Runtime.enable");await command("Page.enable");await command("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:1,mobile:true});await command("Page.navigate",{url:"http://127.0.0.1:4173/?qa=v41"});await waitFor(`window.__monsterGameDiagnostics?.version==='4.1.0'`,12000);
  await evaluate(`window.__seenAttract=[];new MutationObserver(()=>{const id=document.querySelector('.attract-event')?.dataset.event;if(id&&!window.__seenAttract.includes(id))window.__seenAttract.push(id)}).observe(document.querySelector('.living-events'),{childList:true})`);
  await sleep(30000);const home=await evaluate(`({events:window.__seenAttract,overflow:document.documentElement.scrollWidth-innerWidth,layers:document.querySelectorAll('.home-far,.home-mid,.home-foreground').length})`);if(home.events.length<3||home.overflow>1||home.layers!==3)throw Error(`Living home failed ${JSON.stringify(home)}`);await shot("qa-v41-home-30s.png");
  await evaluate(`(()=>{const t=document.querySelector('#menuSoundToggle');t.checked=false;t.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('[data-mode="person"]').click();const e=document.querySelector('#ventInput');e.value='平时什么都不干，领导来了突然特别积极。';e.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#releaseBtn').click()})()`);await waitFor(`document.body.dataset.view==='battleView'&&window.__monsterGameDiagnostics?.combat`);await evaluate(`window.__v41QA.forceWeapon('chainsaw')`);await waitFor(`document.querySelector('.weapon-chainsaw')`);await evaluate(`document.querySelector('.weapon-chainsaw').click()`);await press(".monster-wrap.target",1500,35,0);const battle=await evaluate(`({weapon:window.__monsterGameDiagnostics.weapon,props:[...document.querySelectorAll('.arena-prop svg')].length,architecture:!!document.querySelector('.arena-architecture')})`);if(!battle.weapon?.used.includes("chainsaw")||battle.props<3||!battle.architecture)throw Error(`Weapon/arena failed ${JSON.stringify(battle)}`);await shot("qa-v41-chainsaw.png");
  for(let i=0;i<30&&!await evaluate(`window.__monsterGameDiagnostics.combat.mode==='release'`);i++)await press(".monster-wrap.target",520);
  await waitFor(`window.__monsterGameDiagnostics.combat.mode==='release'`);await waitFor(`document.querySelector('.toybox-layer.sandbox')`);await sleep(3500);const release=await evaluate(`({mode:window.__monsterGameDiagnostics.combat.mode,finish:window.__monsterGameDiagnostics.combat.canFinish,stage:document.querySelector('.arena-world')?.dataset.stage,weaponDrops:document.querySelectorAll('.weapon-drop').length})`);if(release.mode!=="release"||release.stage!=="release"||release.weaponDrops<1)throw Error(`Release sandbox failed ${JSON.stringify(release)}`);await shot("qa-v41-release.png");
  await evaluate(`document.querySelector('#battleView [data-back="home"]').click()`);await waitFor(`document.body.dataset.view==='homeView'`);await sleep(250);const clean=await evaluate(`({canvas:document.querySelectorAll('canvas').length,sources:window.__monsterGameDiagnostics.audio.liveSources,encounter:window.__monsterGameDiagnostics.encounter,weapon:window.__monsterGameDiagnostics.weapon})`);if(clean.canvas||clean.sources||clean.encounter||clean.weapon)throw Error(`Cleanup failed ${JSON.stringify(clean)}`);if(errors.length)throw Error(errors.join(" | "));
  console.log(JSON.stringify({ok:true,home,battle,release,clean},null,2));
}finally{try{ws?.close()}catch{}browser.kill();await sleep(150);await rm(profile,{recursive:true,force:true})}
